name: Test build filters and patches

on:
  # For manual run builds
  workflow_dispatch:
  push:
    paths-ignore:
      # do not trigger build on changes to the following files.
      # it is needed to avoid pull request merge blocking
      # as compiler does not use the updated config during the build.
      - 'optimization_config.json'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      # TODO: add a separate workflow for linting
      - name: Lint code
        run: yarn lint

      - name: Build filters
        run: TLS=insecure yarn build

      - name: Build patches
        # Does not matter how long patches are
        # valid because these patches (as well as filter)
        # would not be merged to master.
        run: yarn build:patches --time=3600 --resolution=s

      - name: Validate platforms and locales
        run: yarn validate
